name: biliresp
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy>=1.21
  - networkx>=3.1
  - rdkit>=2023.9.5
  - scipy>=1.12
  - pyyaml>=6.0
  - pip
  - pytest>=8.0
  - mkdocs>=1.6
  - pymdown-extensions>=10.0
