- group_charge: 1.0
  constraint_indices: [6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]
- group_charge: 0.0
  constraint_indices: [0,1,2,3,4,5]
- group_charge: 0.0
  constraint_indices: [24,25,26,27,28,29]
