- group_charge: 2.4109
  constraint_indices: [10,11,12,13,14,15,16,17,18,19,20,21]
- group_charge: 0.0
  constraint_indices: [0,1,2,3,4,5]
- group_charge: 0.0
  constraint_indices: [24,25,26,27,28,29]
